spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/king-admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level: debug
